[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Self encrypting files (convergent encryption plus obfuscation)"
documentation = "https://docs.rs/self_encryption"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "self_encryption"
readme = "README.md"
repository = "https://github.com/maidsafe/self_encryption"
version = "0.8.0"

[dependencies]
brotli2 = "~0.2.1"
memmap = "~0.4.0"
rand = "~0.3.14"
rust_sodium = { git = "https://github.com/maqi/rust_sodium", branch = "update" }
serde = "~1.0.2"
serde_derive = "~1.0.2"
tiny-keccak = "~1.2.1"
unwrap = "~1.1.0"

[dev-dependencies]
docopt = "~0.6.86"
rustc-serialize = "~0.3.23"
itertools = "~0.5.2"
maidsafe_utilities = { git = "https://github.com/maqi/maidsafe_utilities", branch = "update" }

[[example]]
bench = false
name = "basic_encryptor"
