[package]
name = "self_encryption"
version = "0.2.1"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Self encrypting files (convergent encryption plus obfuscation)"
documentation = "http://maidsafe.net/self_encryption/latest"
repository = "https://github.com/maidsafe/self_encryption"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
asynchronous = "*"
cbor = "*"
docopt = "*"
rustc-serialize = "*"
maidsafe_sodiumoxide = "*"
tempdir = "*"
flate2 = "*"

[dev-dependencies]
rand = "*"

[[example]]
name = "basic_encryptor"
path = "examples/basic_encryptor.rs"
test = true
bench = false
