[package]
authors = [ "MaidSafe Developers <dev@maidsafe.net>" ]
description = "Self encrypting files (convergent encryption plus obfuscation)"
documentation = "https://docs.rs/self_encryption"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "self_encryption"
readme = "README.md"
repository = "https://github.com/maidsafe/self_encryption"
version = "0.19.1"

[dependencies]
async-trait = "~0.1.30"
aes = "~0.3.2"
block-modes = "~0.3.3"
bincode = "1.2.1"
brotli = "3.3.0"
futures = "~0.3.4"
rand = "~0.7.3"
rand_chacha = "~0.2.2"
tiny-keccak = "1.5.0"
err-derive = "0.2.4"

  [dependencies.serde]
  version = "1.0.97"
  features = [ "derive" ]

  [dependencies.tokio]
  version = "~0.2.18"
  features = [ "rt-core", "macros" ]

[dev-dependencies]
criterion = "~0.3"
rustc-serialize = "~0.3.24"
docopt = "~0.9.0"
itertools = "~0.8.0"

[[example]]
bench = false
name = "basic_encryptor"

[[bench]]
name = "lib"
harness = false
