[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Self encrypting files (convergent encryption plus obfuscation)"
documentation = "https://docs.rs/self_encryption"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "self_encryption"
readme = "README.md"
repository = "https://github.com/maidsafe/self_encryption"
version = "0.12.0"

[dependencies]
brotli = "~2.1.0"
futures = "~0.1.15"
memmap = "~0.5.2"
rand = "~0.3.15"
safe_crypto = "~0.3.0"
serde = "~1.0.24"
serde_derive = "~1.0.24"
unwrap = "~1.1.0"

[dev-dependencies]
rustc-serialize = "~0.3.24"
docopt = "~0.8.1"
itertools = "~0.6.1"
maidsafe_utilities = "~0.15.0"

[[example]]
bench = false
name = "basic_encryptor"
