[package]

name = "self_encryption"
version = "0.1.1"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Self encrypting files (convergent encryption plus obfuscation)"
documentation = "http://rust-ci.org/dirvine/self_encryption"
repository = "https://github.com/dirvine/self_encryption"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
rand = "*"
tempdir = "*"
docopt = "*"
rustc-serialize = "*"
rust-crypto = "*"
cbor = "*"
asynchronous = "*"
flate2 = "0.2"

[[example]]
name = "basic_encryptor"
path = "examples/basic_encryptor.rs"
test = true
bench = false
