[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Self encrypting files (convergent encryption plus obfuscation)"
documentation = "https://docs.rs/self_encryption"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "self_encryption"
readme = "README.md"
repository = "https://github.com/maidsafe/self_encryption"
version = "0.14.0"

[dependencies]
bincode = "~1.1.4"
brotli = "~3.3.0"
futures = "~0.1.28"
memmap = "~0.7.0"
rand = "~0.6.0"
rand_chacha = "~0.1.1"
rust_sodium = "~0.10.2"
serde = { version = "~1.0.97", features = ["derive"] }
tiny-keccak = "~1.5.0"
unwrap = "~1.2.1"

[dev-dependencies]
rustc-serialize = "~0.3.24"
docopt = "~0.9.0"
itertools = "~0.8.0"

[[example]]
bench = false
name = "basic_encryptor"
