[package]

name = "self_encryption"
version = "0.0.8"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://rust-ci.org/dirvine/self_encryption"
repository = "https://github.com/dirvine/self_encryption"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
rand = "*"
rust-crypto ="*"
tempdir = "*"

[lib]
name = "self_encryption"
bench = false

[[bin]]
name = "se"
path = "examples/self_encryption/main.rs"
test = false
bench = false
